SELECT
  ORDER_ID,
  COALESCE(TRIM(CUSTOMER_NAME), 'Unknown') AS CUSTOMER_NAME,
  TRIM(PRODUCT_NAME) AS PRODUCT_NAME,
  QUANTITY,
  PRICE
FROM sales_data;



SELECT
  ORDER_ID,
  TO_DATE(ORDER_DATE, 'MM/DD/YYYY') AS ORDER_DATE_FORMATTED
FROM sales_data;



SELECT
  ORDER_ID,
  PRODUCT_NAME,
  QUANTITY,
  PRICE,
  QUANTITY * PRICE AS TOTAL_REVENUE
FROM sales_data;



SELECT
  QUANTITY,
  PRICE
FROM sales_data
WHERE QUANTITY < 0 OR PRICE < 0;


SELECT
  PRODUCT_NAME,
  SUM(QUANTITY) AS TOTAL_UNITS_SOLD,
  SUM(QUANTITY * PRICE) AS TOTAL_REVENUE
FROM sales_data
GROUP BY PRODUCT_NAME
ORDER BY TOTAL_REVENUE DESC;


CREATE OR REPLACE VIEW sales_data_transformed AS
WITH cleaned_data AS (
  SELECT
    ORDER_ID,
    COALESCE(TRIM(CUSTOMER_NAME), 'Unknown') AS CUSTOMER_NAME,
    TRIM(PRODUCT_NAME) AS PRODUCT_NAME,
    QUANTITY,
    PRICE,
    TO_DATE(ORDER_DATE, 'MM/DD/YYYY') AS ORDER_DATE_FORMATTED,
    QUANTITY * PRICE AS TOTAL_REVENUE
  FROM sales_data_raw
)
SELECT * FROM cleaned_data;


SELECT
  Symbol,
  Date,
  Close,
  AVG(Close) OVER (
    PARTITION BY Symbol
    ORDER BY TO_DATE(Date)
    ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
  ) AS Moving_Avg_3_Day
FROM market_data
ORDER BY Symbol, Date;